### ISSUE TITLE
PLY.load() got java.io.IOException: [Line 17] could not parse 'property list uchar float texcoord'

### ISSUE THREAD

**Issue by chunkitlau** [DirkToewe/sjmply#2]
I am try to open a ply file with sjmply. However, I encountered an error “ java.io.IOException: [Line 17] could not parse 'property list uchar float texcoord' ” when run code "PLY.load()". PS: ply file attached with google drive: https://drive.google.com/file/d/1R5wFJNFU96VFhEeeIEl6Y6d566pqmsQN/view

**Comment by DirkToewe** [comment]
Looks like there was a pair of parantheses missing in a regular expression. Should be fixed with 2a696ec79994c3af0bf555b4e3b2513eb308b4d2.

**Comment by chunkitlau** [comment]
> Looks like there was a pair of parantheses missing in a regular expression. Should be fixed with [2a696ec](https://github.com/DirkToewe/sjmply/commit/2a696ec79994c3af0bf555b4e3b2513eb308b4d2).

Problem solved. Thanks a lot.
