### ISSUE TITLE
How to modify the attributes of a vertex?

### ISSUE THREAD

**Issue by chunkitlau** [DirkToewe/sjmply#3]
I can get the x coordinate of the vertex by using bunny.elements("vertex").propertyAs(FLOAT64,"x"). However, I want to change the value of x coordinate of some vertices. How can I do that? Thanks in advance.

**Comment by DirkToewe** [comment]
If You use `bunny.elements("vertex").property(FLOAT64,"x")` instead of `propertyAs`, the returned array can be manipulated directly to change the x-coordinates. If `x` is not of type `FLOAT64` yet, You have to convert it first via `bunny.elements("vertex").convertProperty( "x", FLOAT64 )`.

**Comment by chunkitlau** [comment]
> If You use `bunny.elements("vertex").property(FLOAT64,"x")` instead of `propertyAs`, the returned array can be manipulated directly to change the x-coordinates. If `x` is not of type `FLOAT64` yet, You have to convert it first via `bunny.elements("vertex").convertProperty( "x", FLOAT64 )`.

Thanks a lot.
