### ISSUE TITLE
Is there any good way to render the ply file into an image (like jpg or png) ?

### ISSUE THREAD

**Issue by chunkitlau** [DirkToewe/sjmply#4]

**Comment by DirkToewe** [comment]
If you want to take screenshots manually, the easiest way would be to use the `PLY_Plotly` utilities. The Plotly HTML view allows You to take screenshots with a button in the upper right corner.

![plotly_take_screenshot](https://user-images.githubusercontent.com/8115342/133286668-af250c0d-ca6a-40d3-8279-efa64ca1cafa.png)

For anything more than that, You are going to have to use some other 3D library like [JMonkey](https://github.com/jMonkeyEngine/jmonkeyengine).

**Comment by chunkitlau** [comment]
I want to render the image (to png or jpg) directly, is there any easy way (for example some api) ?

**Comment by DirkToewe** [comment]
Not with `sjmply`. My experience with 3D engines, especially in combination with Android, is limited, so I cannot give You good suggestion, I'm afraid.

**Comment by chunkitlau** [comment]
Thanks anyway.
